services:
  staff-socket:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8799:8788"
    environment:
      NODE_ENV: development
    restart: unless-stopped
    volumes:
      - ./logs:/logs
    deploy:
      resources:
        limits:
          memory: 128M
